### ISSUE TITLE
Add some famous dsa problems and their solutions

### ISSUE THREAD

**Issue by vishal8113** [vishal8113/Hacktoberfest-2024#1]

**Comment by singhvibhanshu** [comment]
can you provide detailed description of the problem?

**Comment by sanjeevidev** [comment]
Can i use python or only CPP ?

**Comment by vishal8113** [comment]
You can use any language whichever you wish

**Comment by vishal8113** [comment]
@singhvibhanshu You have to add famous dsa problems solution by mentioning the problem statement, You can write solution in any language

**Comment by askarthikey** [comment]
hey @vishal8113 can i add The Sieve of Eratosthenes  to this in c++

**Comment by vishal8113** [comment]
@askarthikey yes u can

**Comment by Rajansharma44** [comment]
https://meet.google.com/abv-ghyr-fcv

**Comment by shivam-1810** [comment]
@vishal8113 Assign to me also, I will add some really cool algorithms with problem statement.

**Comment by singhvibhanshu** [comment]
@vishal8113 okay sir.

**Comment by Smriti-Prajapati** [comment]
Hey please assign this issue to me for Hactoberfest.

**Comment by SreejaMandla** [comment]
hi, could you please assign this issue to me?

**Comment by vishal8113** [comment]
@SreejaMandla done

**Comment by priyansh2313** [comment]
i would like to get assigned, sir

**Comment by Pariyul** [comment]
I want to add some problem kindly assign me

**Comment by vishal8113** [comment]
@Pariyul Done

**Comment by Pariyul** [comment]
kindly merge my pull request

**Comment by sehajbansal** [comment]
@vishal8113  please assign me the issue

**Comment by Ishita-Trivedi** [comment]
I'm an enthusiastic problem solver and would love to contribute some insightful, intuitive problems to this project. @vishal8113 Could you please assign this issue to me?

**Comment by vishal8113** [comment]
@Ishita-Trivedi done

**Comment by Samyak137** [comment]
Will you please assign it to me.

**Comment by vishal8113** [comment]
@Samyak137 done

**Comment by Bhabuk10** [comment]
@vishal8113  I would like to get assigned this issue

**Comment by vishal8113** [comment]
@Bhabuk10 Done

**Comment by cherishwish** [comment]
Hi. Please assign this issue to me if possible!

**Comment by vishal8113** [comment]
@cherishwish done

**Comment by Samyak137** [comment]
I am not able to generate PR due to some technical glitch in Git, will you please assign me again

**Comment by vishal8113** [comment]
@Samyak137 done

**Comment by mehulvyas104** [comment]
Please assign me this issue

**Comment by tush47** [comment]
@vishal8113 i have recently made PR's for this issue, have a look to merge them.

**Comment by AyushKumar55** [comment]
@vishal8113 
Assign me this issue. Will add some GreedyAlgo Problems.

**Comment by Prax860** [comment]
assign me this please
